services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: backend
    command: npm run start:dev
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - database
    volumes:
      - ./src:/app/src
    
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root