services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: backend
    command: npm run start:dev
    environment:
      - PORT=8080
      - DATABASE_NAME=classroom
      - DATABASE_USER=root
      - DATABASE_PASS=root
      - DATABASE_URI=mongodb://database:27017
    ports:
      - '8080:8080'
    depends_on:
      - database
    volumes:
      - ./src:/app/src
    
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: classroom
      MONGO_INITDB_ROOT_PASSWORD: root