name: Auto Merge Branch

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!dev'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          title: "Auto-merge changes"
          body: "Automatically created pull request for changes in branch ${{ github.event.ref }}"
          labels: "auto-merge"

      - name: Merge Pull Request
        if: steps.create_pr.outputs.pull-request-number
        run: gh pr merge ${{ steps.create_pr.outputs.pull-request-number }} --auto

      - name: Delete Branch
        if: success() && steps.create_pr.outputs.pull-request-number
        run: gh pr close ${{ steps.create_pr.outputs.pull-request-number }} --delete-branch
